# Generated by Django 5.2.6 on 2025-09-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('consent', models.BooleanField(default=False)),
                ('consent_version', models.CharField(default='v1.0', max_length=10)),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
